export default [{
    "english": "😀",
    "chinese": "\n"
}, {
    "english": "😁",
    "chinese": "\n"
}, {
    "english": "😂",
    "chinese": "\n"
}, {
    "english": "😃",
    "chinese": "\n"
}, {
    "english": "😄",
    "chinese": "\n"
}, {
    "english": "😅",
    "chinese": "\n"
}, {
    "english": "😆",
    "chinese": "\n"
}, {
    "english": "😉",
    "chinese": "\n"
}, {
    "english": "😊",
    "chinese": "\n"
}, {
    "english": "😋",
    "chinese": "\n"
}, {
    "english": "😎",
    "chinese": "\n"
}, {
    "english": "😍",
    "chinese": "\n"
}, {
    "english": "😘",
    "chinese": "\n"
}, {
    "english": "😗",
    "chinese": "\n"
}, {
    "english": "😙",
    "chinese": "\n"
}, {
    "english": "😚",
    "chinese": "\n"
}, {
    "english": "😇",
    "chinese": "\n"
}, {
    "english": "😐",
    "chinese": "\n"
}, {
    "english": "😑",
    "chinese": "\n"
}, {
    "english": "😶",
    "chinese": "\n"
}, {
    "english": "😏",
    "chinese": "\n"
}, {
    "english": "😣",
    "chinese": "\n"
}, {
    "english": "😥",
    "chinese": "\n"
}, {
    "english": "😮",
    "chinese": "\n"
}, {
    "english": "😯",
    "chinese": "\n"
}, {
    "english": "😪",
    "chinese": "\n"
}, {
    "english": "😫",
    "chinese": "\n"
}, {
    "english": "😴",
    "chinese": "\n"
}, {
    "english": "😌",
    "chinese": "\n"
}, {
    "english": "😛",
    "chinese": "\n"
}, {
    "english": "😜",
    "chinese": "\n"
}, {
    "english": "😝",
    "chinese": "\n"
}, {
    "english": "😒",
    "chinese": "\n"
}, {
    "english": "😓",
    "chinese": "\n"
}, {
    "english": "😔",
    "chinese": "\n"
}, {
    "english": "😕",
    "chinese": "\n"
}, {
    "english": "😲",
    "chinese": "\n"
}, {
    "english": "😷",
    "chinese": "\n"
}, {
    "english": "😖",
    "chinese": "\n"
}, {
    "english": "😞",
    "chinese": "\n"
}, {
    "english": "😟",
    "chinese": "\n"
}, {
    "english": "😤",
    "chinese": "\n"
}, {
    "english": "😢",
    "chinese": "\n"
}, {
    "english": "😭",
    "chinese": "\n"
}, {
    "english": "😦",
    "chinese": "\n"
}, {
    "english": "😧",
    "chinese": "\n"
}, {
    "english": "😨",
    "chinese": "\n"
}, {
    "english": "😬",
    "chinese": "\n"
}, {
    "english": "😰",
    "chinese": "\n"
}, {
    "english": "😱",
    "chinese": "\n"
}, {
    "english": "😳",
    "chinese": "\n"
}, {
    "english": "😵",
    "chinese": "\n"
}, {
    "english": "😡",
    "chinese": "\n"
}, {
    "english": "😠",
    "chinese": ""
}, {
    "english": "👦",
    "chinese": "\n"
}, {
    "english": "👧",
    "chinese": "\n"
}, {
    "english": "👨",
    "chinese": "\n"
}, {
    "english": "👩",
    "chinese": "\n"
}, {
    "english": "👴",
    "chinese": "\n"
}, {
    "english": "👵",
    "chinese": "\n"
}, {
    "english": "👶",
    "chinese": "\n"
}, {
    "english": "👱",
    "chinese": "\n"
}, {
    "english": "👮",
    "chinese": "\n"
}, {
    "english": "👲",
    "chinese": "\n"
}, {
    "english": "👳",
    "chinese": "\n"
}, {
    "english": "👷",
    "chinese": "\n"
}, {
    "english": "👸",
    "chinese": "\n"
}, {
    "english": "💂",
    "chinese": "\n"
}, {
    "english": "🎅",
    "chinese": "\n"
}, {
    "english": "👰",
    "chinese": "\n"
}, {
    "english": "👼",
    "chinese": "\n"
}, {
    "english": "💆",
    "chinese": "\n"
}, {
    "english": "💇",
    "chinese": "\n"
}, {
    "english": "🙍",
    "chinese": "\n"
}, {
    "english": "🙎",
    "chinese": "\n"
}, {
    "english": "🙅",
    "chinese": "\n"
}, {
    "english": "🙆",
    "chinese": "\n"
}, {
    "english": "💁",
    "chinese": "\n"
}, {
    "english": "🙋",
    "chinese": "\n"
}, {
    "english": "🙇",
    "chinese": "\n"
}, {
    "english": "🙌",
    "chinese": "\n"
}, {
    "english": "🙏",
    "chinese": "\n"
}, {
    "english": "👤",
    "chinese": "\n"
}, {
    "english": "👥",
    "chinese": "\n"
}, {
    "english": "🚶",
    "chinese": "\n"
}, {
    "english": "🏃",
    "chinese": "\n"
}, {
    "english": "👯",
    "chinese": "\n"
}, {
    "english": "💃",
    "chinese": "\n"
}, {
    "english": "👫",
    "chinese": "\n"
}, {
    "english": "👬",
    "chinese": "\n"
}, {
    "english": "👭",
    "chinese": "\n"
}, {
    "english": "💏",
    "chinese": "\n"
}, {
    "english": "💑",
    "chinese": "\n"
}, {
    "english": "👪",
    "chinese": ""
}, {
    "english": "💪",
    "chinese": "\n"
}, {
    "english": "👉",
    "chinese": "\n"
}, {
    "english": "☝",
    "chinese": "\n"
}, {
    "english": "👆",
    "chinese": "\n"
}, {
    "english": "👇",
    "chinese": "\n"
}, {
    "english": "✌",
    "chinese": "\n"
}, {
    "english": "✋",
    "chinese": "\n"
}, {
    "english": "👌",
    "chinese": "\n"
}, {
    "english": "👍",
    "chinese": "\n"
}, {
    "english": "👎",
    "chinese": "\n"
}, {
    "english": "✊",
    "chinese": "\n"
}, {
    "english": "👊",
    "chinese": "\n"
}, {
    "english": "👋",
    "chinese": "\n"
}, {
    "english": "👏",
    "chinese": "\n"
}, {
    "english": "👐",
    "chinese": "\n"
}, {
    "english": "✍",
    "chinese": ""
}, {
    "english": "👣\n",
    "chinese": ""
}, {
    "english": "👀\n",
    "chinese": ""
}, {
    "english": "👂\n",
    "chinese": ""
}, {
    "english": "👃\n",
    "chinese": ""
}, {
    "english": "👅\n",
    "chinese": ""
}, {
    "english": "👄\n",
    "chinese": ""
}, {
    "english": "💋\n",
    "chinese": ""
}, {
    "english": "👓\n",
    "chinese": ""
}, {
    "english": "👔\n",
    "chinese": ""
}, {
    "english": "👕\n",
    "chinese": ""
}, {
    "english": "👖\n",
    "chinese": ""
}, {
    "english": "👗\n",
    "chinese": ""
}, {
    "english": "👘\n",
    "chinese": ""
}, {
    "english": "👙\n",
    "chinese": ""
}, {
    "english": "👚\n",
    "chinese": ""
}, {
    "english": "👛\n",
    "chinese": ""
}, {
    "english": "👜\n",
    "chinese": ""
}, {
    "english": "👝\n",
    "chinese": ""
}, {
    "english": "🎒\n",
    "chinese": ""
}, {
    "english": "💼\n",
    "chinese": ""
}, {
    "english": "👞\n",
    "chinese": ""
}, {
    "english": "👟\n",
    "chinese": ""
}, {
    "english": "👠\n",
    "chinese": ""
}, {
    "english": "👡\n",
    "chinese": ""
}, {
    "english": "👢\n",
    "chinese": ""
}, {
    "english": "👑\n",
    "chinese": ""
}, {
    "english": "👒\n",
    "chinese": ""
}, {
    "english": "🎩\n",
    "chinese": ""
}, {
    "english": "🎓\n",
    "chinese": ""
}, {
    "english": "💄\n",
    "chinese": ""
}, {
    "english": "💅\n",
    "chinese": ""
}, {
    "english": "💍\n",
    "chinese": ""
}, {
    "english": "🌂\n",
    "chinese": ""
}, {
    "english": "📱\n",
    "chinese": ""
}, {
    "english": "📲\n",
    "chinese": ""
}, {
    "english": "📶\n",
    "chinese": ""
}, {
    "english": "📳\n",
    "chinese": ""
}, {
    "english": "📴\n",
    "chinese": ""
}, {
    "english": "☎\n",
    "chinese": ""
}, {
    "english": "📞\n",
    "chinese": ""
}, {
    "english": "📟\n",
    "chinese": ""
}, {
    "english": "📠\n",
    "chinese": ""
}, {
    "english": "♻\n",
    "chinese": ""
}, {
    "english": "🏧\n",
    "chinese": ""
}, {
    "english": "🚮\n",
    "chinese": ""
}, {
    "english": "🚰\n",
    "chinese": ""
}, {
    "english": "♿\n",
    "chinese": ""
}, {
    "english": "🚹\n",
    "chinese": ""
}, {
    "english": "🚺\n",
    "chinese": ""
}, {
    "english": "🚻\n",
    "chinese": ""
}, {
    "english": "🚼\n",
    "chinese": ""
}, {
    "english": "🚾\n",
    "chinese": ""
}, {
    "english": "⚠\n",
    "chinese": ""
}, {
    "english": "🚸\n",
    "chinese": ""
}, {
    "english": "⛔\n",
    "chinese": ""
}, {
    "english": "🚫\n",
    "chinese": ""
}, {
    "english": "🚳\n",
    "chinese": ""
}, {
    "english": "🚭\n",
    "chinese": ""
}, {
    "english": "🚯\n",
    "chinese": ""
}, {
    "english": "🚱\n",
    "chinese": ""
}, {
    "english": "🚷\n",
    "chinese": ""
}, {
    "english": "🔞\n",
    "chinese": ""
}, {
    "english": "💈",
    "chinese": ""
}, {
    "english": "🙈\n",
    "chinese": ""
}, {
    "english": "🙉\n",
    "chinese": ""
}, {
    "english": "🙊\n",
    "chinese": ""
}, {
    "english": "🐵\n",
    "chinese": ""
}, {
    "english": "🐒\n",
    "chinese": ""
}, {
    "english": "🐶\n",
    "chinese": ""
}, {
    "english": "🐕\n",
    "chinese": ""
}, {
    "english": "🐩\n",
    "chinese": ""
}, {
    "english": "🐺\n",
    "chinese": ""
}, {
    "english": "🐱\n",
    "chinese": ""
}, {
    "english": "😺\n",
    "chinese": ""
}, {
    "english": "😸\n",
    "chinese": ""
}, {
    "english": "😹\n",
    "chinese": ""
}, {
    "english": "😻\n",
    "chinese": ""
}, {
    "english": "😼\n",
    "chinese": ""
}, {
    "english": "😽\n",
    "chinese": ""
}, {
    "english": "🙀\n",
    "chinese": ""
}, {
    "english": "😿\n",
    "chinese": ""
}, {
    "english": "😾\n",
    "chinese": ""
}, {
    "english": "🐈\n",
    "chinese": ""
}, {
    "english": "🐯\n",
    "chinese": ""
}, {
    "english": "🐅\n",
    "chinese": ""
}, {
    "english": "🐆\n",
    "chinese": ""
}, {
    "english": "🐴\n",
    "chinese": ""
}, {
    "english": "🐎\n",
    "chinese": ""
}, {
    "english": "🐮\n",
    "chinese": ""
}, {
    "english": "🐂\n",
    "chinese": ""
}, {
    "english": "🐃\n",
    "chinese": ""
}, {
    "english": "🐄\n",
    "chinese": ""
}, {
    "english": "🐷\n",
    "chinese": ""
}, {
    "english": "🐖\n",
    "chinese": ""
}, {
    "english": "🐗\n",
    "chinese": ""
}, {
    "english": "🐽\n",
    "chinese": ""
}, {
    "english": "🐏\n",
    "chinese": ""
}, {
    "english": "🐑\n",
    "chinese": ""
}, {
    "english": "🐐\n",
    "chinese": ""
}, {
    "english": "🐪\n",
    "chinese": ""
}, {
    "english": "🐫\n",
    "chinese": ""
}, {
    "english": "🐘\n",
    "chinese": ""
}, {
    "english": "🐭\n",
    "chinese": ""
}, {
    "english": "🐁\n",
    "chinese": ""
}, {
    "english": "🐀\n",
    "chinese": ""
}, {
    "english": "🐹\n",
    "chinese": ""
}, {
    "english": "🐰\n",
    "chinese": ""
}, {
    "english": "🐇\n",
    "chinese": ""
}, {
    "english": "🐻\n",
    "chinese": ""
}, {
    "english": "🐨\n",
    "chinese": ""
}, {
    "english": "🐼\n",
    "chinese": ""
}, {
    "english": "🐾\n",
    "chinese": ""
}, {
    "english": "🐔\n",
    "chinese": ""
}, {
    "english": "🐓\n",
    "chinese": ""
}, {
    "english": "🐣\n",
    "chinese": ""
}, {
    "english": "🐤\n",
    "chinese": ""
}, {
    "english": "🐥\n",
    "chinese": ""
}, {
    "english": "🐦\n",
    "chinese": ""
}, {
    "english": "🐧\n",
    "chinese": ""
}, {
    "english": "🐸\n",
    "chinese": ""
}, {
    "english": "🐊\n",
    "chinese": ""
}, {
    "english": "🐢\n",
    "chinese": ""
}, {
    "english": "🐍\n",
    "chinese": ""
}, {
    "english": "🐲\n",
    "chinese": ""
}, {
    "english": "🐉\n",
    "chinese": ""
}, {
    "english": "🐳\n",
    "chinese": ""
}, {
    "english": "🐋\n",
    "chinese": ""
}, {
    "english": "🐬\n",
    "chinese": ""
}, {
    "english": "🐟\n",
    "chinese": ""
}, {
    "english": "🐠\n",
    "chinese": ""
}, {
    "english": "🐡\n",
    "chinese": ""
}, {
    "english": "🐙\n",
    "chinese": ""
}, {
    "english": "🐚\n",
    "chinese": ""
}, {
    "english": "🐌\n",
    "chinese": ""
}, {
    "english": "🐛\n",
    "chinese": ""
}, {
    "english": "🐜\n",
    "chinese": ""
}, {
    "english": "🐝\n",
    "chinese": ""
}, {
    "english": "🐞\n",
    "chinese": ""
}, {
    "english": "🦋",
    "chinese": ""
}, {
    "english": "💐\n",
    "chinese": ""
}, {
    "english": "🌸\n",
    "chinese": ""
}, {
    "english": "💮\n",
    "chinese": ""
}, {
    "english": "🌹\n",
    "chinese": ""
}, {
    "english": "🌺\n",
    "chinese": ""
}, {
    "english": "🌻\n",
    "chinese": ""
}, {
    "english": "🌼\n",
    "chinese": ""
}, {
    "english": "🌷\n",
    "chinese": ""
}, {
    "english": "🌱\n",
    "chinese": ""
}, {
    "english": "🌲\n",
    "chinese": ""
}, {
    "english": "🌳\n",
    "chinese": ""
}, {
    "english": "🌴\n",
    "chinese": ""
}, {
    "english": "🌵\n",
    "chinese": ""
}, {
    "english": "🌾\n",
    "chinese": ""
}, {
    "english": "🌿\n",
    "chinese": ""
}, {
    "english": "🍀\n",
    "chinese": ""
}, {
    "english": "🍁\n",
    "chinese": ""
}, {
    "english": "🍂\n",
    "chinese": ""
}, {
    "english": "🍃",
    "chinese": ""
}, {
    "english": "🌍\n",
    "chinese": ""
}, {
    "english": "🌎\n",
    "chinese": ""
}, {
    "english": "🌏\n",
    "chinese": ""
}, {
    "english": "🌐\n",
    "chinese": ""
}, {
    "english": "🌑\n",
    "chinese": ""
}, {
    "english": "🌒\n",
    "chinese": ""
}, {
    "english": "🌓\n",
    "chinese": ""
}, {
    "english": "🌔\n",
    "chinese": ""
}, {
    "english": "🌕\n",
    "chinese": ""
}, {
    "english": "🌖\n",
    "chinese": ""
}, {
    "english": "🌗\n",
    "chinese": ""
}, {
    "english": "🌘\n",
    "chinese": ""
}, {
    "english": "🌙\n",
    "chinese": ""
}, {
    "english": "🌚\n",
    "chinese": ""
}, {
    "english": "🌛\n",
    "chinese": ""
}, {
    "english": "🌜\n",
    "chinese": ""
}, {
    "english": "☀\n",
    "chinese": ""
}, {
    "english": "🌝\n",
    "chinese": ""
}, {
    "english": "🌞\n",
    "chinese": ""
}, {
    "english": "⭐\n",
    "chinese": ""
}, {
    "english": "🌟\n",
    "chinese": ""
}, {
    "english": "🌠\n",
    "chinese": ""
}, {
    "english": "☁\n",
    "chinese": ""
}, {
    "english": "⛅\n",
    "chinese": ""
}, {
    "english": "☔\n",
    "chinese": ""
}, {
    "english": "⚡\n",
    "chinese": ""
}, {
    "english": "❄\n",
    "chinese": ""
}, {
    "english": "🔥\n",
    "chinese": ""
}, {
    "english": "💧\n",
    "chinese": ""
}, {
    "english": "🌊",
    "chinese": ""
}, {
    "english": "🍇\n",
    "chinese": ""
}, {
    "english": "🍈\n",
    "chinese": ""
}, {
    "english": "🍉\n",
    "chinese": ""
}, {
    "english": "🍊\n",
    "chinese": ""
}, {
    "english": "🍋\n",
    "chinese": ""
}, {
    "english": "🍌\n",
    "chinese": ""
}, {
    "english": "🍍\n",
    "chinese": ""
}, {
    "english": "🍎\n",
    "chinese": ""
}, {
    "english": "🍏\n",
    "chinese": ""
}, {
    "english": "🍐\n",
    "chinese": ""
}, {
    "english": "🍑\n",
    "chinese": ""
}, {
    "english": "🍒\n",
    "chinese": ""
}, {
    "english": "🍓\n",
    "chinese": ""
}, {
    "english": "🍅\n",
    "chinese": ""
}, {
    "english": "🍆\n",
    "chinese": ""
}, {
    "english": "🌽\n",
    "chinese": ""
}, {
    "english": "🍄\n",
    "chinese": ""
}, {
    "english": "🌰\n",
    "chinese": ""
}, {
    "english": "🍞\n",
    "chinese": ""
}, {
    "english": "🍖\n",
    "chinese": ""
}, {
    "english": "🍗\n",
    "chinese": ""
}, {
    "english": "🍔\n",
    "chinese": ""
}, {
    "english": "🍟\n",
    "chinese": ""
}, {
    "english": "🍕\n",
    "chinese": ""
}, {
    "english": "🍳\n",
    "chinese": ""
}, {
    "english": "🍲\n",
    "chinese": ""
}, {
    "english": "🍱\n",
    "chinese": ""
}, {
    "english": "🍘\n",
    "chinese": ""
}, {
    "english": "🍙\n",
    "chinese": ""
}, {
    "english": "🍚\n",
    "chinese": ""
}, {
    "english": "🍛\n",
    "chinese": ""
}, {
    "english": "🍜\n",
    "chinese": ""
}, {
    "english": "🍝\n",
    "chinese": ""
}, {
    "english": "🍠\n",
    "chinese": ""
}, {
    "english": "🍢\n",
    "chinese": ""
}, {
    "english": "🍣\n",
    "chinese": ""
}, {
    "english": "🍤\n",
    "chinese": ""
}, {
    "english": "🍥\n",
    "chinese": ""
}, {
    "english": "🍡\n",
    "chinese": ""
}, {
    "english": "🍦\n",
    "chinese": ""
}, {
    "english": "🍧\n",
    "chinese": ""
}, {
    "english": "🍨\n",
    "chinese": ""
}, {
    "english": "🍩\n",
    "chinese": ""
}, {
    "english": "🍪\n",
    "chinese": ""
}, {
    "english": "🎂\n",
    "chinese": ""
}, {
    "english": "🍰\n",
    "chinese": ""
}, {
    "english": "🍫\n",
    "chinese": ""
}, {
    "english": "🍬\n",
    "chinese": ""
}, {
    "english": "🍭\n",
    "chinese": ""
}, {
    "english": "🍮\n",
    "chinese": ""
}, {
    "english": "🍯\n",
    "chinese": ""
}, {
    "english": "🍼\n",
    "chinese": ""
}, {
    "english": "☕\n",
    "chinese": ""
}, {
    "english": "🍵\n",
    "chinese": ""
}, {
    "english": "🍶\n",
    "chinese": ""
}, {
    "english": "🍷\n",
    "chinese": ""
}, {
    "english": "🍸\n",
    "chinese": ""
}, {
    "english": "🍹\n",
    "chinese": ""
}, {
    "english": "🍺\n",
    "chinese": ""
}, {
    "english": "🍻\n",
    "chinese": ""
}, {
    "english": "🍴",
    "chinese": ""
}]