export default [{
    "english": "tentacle",
    "chinese": "触手\r\n"
}, {
    "english": "hairjob",
    "chinese": "发交\r\n"
}, {
    "english": "oral/fellatio",
    "chinese": "口交\r\n"
}, {
    "english": "deepthroat",
    "chinese": "深喉\r\n"
}, {
    "english": "gokkun",
    "chinese": "吃精\r\n"
}, {
    "english": "gag",
    "chinese": "口塞\r\n"
}, {
    "english": "ballgag",
    "chinese": "球塞\r\n"
}, {
    "english": "bitgag",
    "chinese": "棍塞\r\n"
}, {
    "english": "ring_gag",
    "chinese": "扩口器\r\n"
}, {
    "english": "cleave_gag",
    "chinese": "用布勒住嘴\r\n"
}, {
    "english": "panty_gag",
    "chinese": "用内裤塞口\r\n"
}, {
    "english": "tapegag",
    "chinese": "胶带封口\r\n"
}, {
    "english": "facial",
    "chinese": "颜射\r\n"
}, {
    "english": "leash",
    "chinese": "宠物链\r\n"
}, {
    "english": "handjob",
    "chinese": "用手做\r\n"
}, {
    "english": "groping",
    "chinese": "摸索\r\n"
}, {
    "english": "areolae",
    "chinese": "乳晕\r\n"
}, {
    "english": "nipples",
    "chinese": "乳头\r\n"
}, {
    "english": "puffy_nipples",
    "chinese": "大乳头\r\n"
}, {
    "english": "small_nipples",
    "chinese": "小乳头\r\n"
}, {
    "english": "nipple_pull",
    "chinese": "啦乳头\r\n"
}, {
    "english": "nipple_torture",
    "chinese": "虐乳头\r\n"
}, {
    "english": "nipple_tweak",
    "chinese": "捏乳头\r\n"
}, {
    "english": "nipple_piercing",
    "chinese": "乳头穿孔\r\n"
}, {
    "english": "breast_grab",
    "chinese": "摸乳\r\n"
}, {
    "english": "lactation",
    "chinese": "哺乳（大范围）\r\n"
}, {
    "english": "breast_sucking/nipple_suck",
    "chinese": "吸乳（中）\r\n"
}, {
    "english": "breast_feeding",
    "chinese": "喂奶(小)\r\n"
}, {
    "english": "paizuri",
    "chinese": "乳交\r\n"
}, {
    "english": "multiple_paizuri",
    "chinese": "多P乳交\r\n"
}, {
    "english": "breast_smother",
    "chinese": "把头塞入胸\r\n"
}, {
    "english": "piercing",
    "chinese": "穿孔\r\n"
}, {
    "english": "navel_piercing",
    "chinese": "肚脐穿孔\r\n"
}, {
    "english": "thigh_sex",
    "chinese": "腿交\r\n"
}, {
    "english": "footjob",
    "chinese": "足交\r\n"
}, {
    "english": "mound_of_venus",
    "chinese": "腹部三角带\r\n"
}, {
    "english": "wide_hips",
    "chinese": "宽盆骨\r\n"
}, {
    "english": "masturbation",
    "chinese": "自慰\r\n"
}, {
    "english": "clothed_masturbation",
    "chinese": "隔着衣服自慰\r\n"
}, {
    "english": "penis",
    "chinese": "阳具/屌\r\n"
}, {
    "english": "testicles",
    "chinese": "睾丸/蛋蛋\r\n"
}, {
    "english": "ejaculation",
    "chinese": "射出\r\n"
}, {
    "english": "cum",
    "chinese": "射精\r\n"
}, {
    "english": "cum_inside",
    "chinese": "内射\r\n"
}, {
    "english": "cum_on_breast",
    "chinese": "射在胸上\r\n"
}, {
    "english": "cum_on_hair",
    "chinese": "射在头发上\r\n"
}, {
    "english": "cum_on_food",
    "chinese": "射在食物上\r\n"
}, {
    "english": "tamakeri",
    "chinese": "蛋疼\r\n"
}, {
    "english": "pussy/vaginal",
    "chinese": "阴户（前者图片远大于后者）\r\n"
}, {
    "english": "pubic_hair",
    "chinese": "阴毛\r\n"
}, {
    "english": "shaved_pussy",
    "chinese": "剃过阴毛的（无毛B）\r\n"
}, {
    "english": "no_pussy",
    "chinese": "没逼的\r\n"
}, {
    "english": "clitoris",
    "chinese": "阴蒂\r\n"
}, {
    "english": "fat_mons",
    "chinese": "肥逼\r\n"
}, {
    "english": "cameltoe",
    "chinese": "骆驼脚趾逼（俗称馒头逼）\r\n"
}, {
    "english": "pussy_juice",
    "chinese": "爱液\r\n"
}, {
    "english": "female_ejaculation",
    "chinese": "潮吹\r\n"
}, {
    "english": "grinding",
    "chinese": "性器摩擦\r\n"
}, {
    "english": "crotch_rub",
    "chinese": "胯部摩擦\r\n"
}, {
    "english": "facesitting",
    "chinese": "坐在脸上\r\n"
}, {
    "english": "cervix",
    "chinese": "子宫口\r\n"
}, {
    "english": "cunnilingus",
    "chinese": "舔阴\r\n"
}, {
    "english": "insertion",
    "chinese": "插入物\r\n"
}, {
    "english": "anal_insertion",
    "chinese": "菊花插入物\r\n"
}, {
    "english": "fruit_insertion",
    "chinese": "用水果蔬菜\r\n"
}, {
    "english": "large_insertion",
    "chinese": "巨大插入\r\n"
}, {
    "english": "penetration",
    "chinese": "异物插入\r\n"
}, {
    "english": "fisting",
    "chinese": "拳头插入\r\n"
}, {
    "english": "fingering",
    "chinese": "手插入\r\n"
}, {
    "english": "multiple_insertions",
    "chinese": "一穴多插\r\n"
}, {
    "english": "double_penetration",
    "chinese": "双穴同插\r\n"
}, {
    "english": "triple_penetration",
    "chinese": "三穴同插\r\n"
}, {
    "english": "double_vaginal",
    "chinese": "双重入穴\r\n"
}, {
    "english": "peeing",
    "chinese": "尿尿\r\n"
}, {
    "english": "have_to_pee",
    "chinese": "憋尿\r\n"
}, {
    "english": "ass",
    "chinese": "屁股\r\n"
}, {
    "english": "huge_ass",
    "chinese": "大屁股\r\n"
}, {
    "english": "spread_ass",
    "chinese": "用手张开屁股\r\n"
}, {
    "english": "buttjob",
    "chinese": "臀交\r\n"
}, {
    "english": "spanked",
    "chinese": "打屁股\r\n"
}, {
    "english": "anus",
    "chinese": "菊花\r\n"
}, {
    "english": "anal",
    "chinese": "爆菊\r\n"
}, {
    "english": "double_anal",
    "chinese": "双重爆菊\r\n"
}, {
    "english": "anal_fingering",
    "chinese": "手爆菊\r\n"
}, {
    "english": "anal_fisting",
    "chinese": "拳爆菊\r\n"
}, {
    "english": "anilingus",
    "chinese": "肛吻\r\n"
}, {
    "english": "enema",
    "chinese": "灌肠\r\n"
}, {
    "english": "stomach_bulge",
    "chinese": "肚子胀\r\n"
}, {
    "english": "x-ray/cross-section/internal_cumshot",
    "chinese": "透视人体内部\r\n"
}, {
    "english": "wakamezake",
    "chinese": "酒倒在阴部\r\n"
}, {
    "english": "public",
    "chinese": "公共场所\r\n"
}, {
    "english": "humiliation",
    "chinese": "羞耻play\r\n"
}, {
    "english": "bra_lift",
    "chinese": "胸罩拉到胸上方\r\n"
}, {
    "english": "panties_around_one_leg",
    "chinese": "内裤挂在一条腿上\r\n"
}, {
    "english": "caught",
    "chinese": "被发现\r\n"
}, {
    "english": "walk-in",
    "chinese": "进门被发现\r\n"
}, {
    "english": "body_writing",
    "chinese": "身上有字\r\n"
}, {
    "english": "tally",
    "chinese": "在身上计数\r\n"
}, {
    "english": "futanari",
    "chinese": "双性\r\n"
}, {
    "english": "incest",
    "chinese": "乱伦\r\n"
}, {
    "english": "twincest",
    "chinese": "兄弟/姐妹/姐弟/兄妹\r\n"
}, {
    "english": "pegging",
    "chinese": "女性使用假屌\r\n"
}, {
    "english": "femdom",
    "chinese": "女奸男（逆推）\r\n"
}, {
    "english": "ganguro",
    "chinese": "日本黑妹\r\n"
}, {
    "english": "bestiality",
    "chinese": "人兽\r\n"
}, {
    "english": "gangbang",
    "chinese": "轮奸\r\n"
}, {
    "english": "threesome",
    "chinese": "3P\r\n"
}, {
    "english": "group_sex/orgy/teamwork",
    "chinese": "群P\r\n"
}, {
    "english": "tribadism",
    "chinese": "磨豆腐\r\n"
}, {
    "english": "molestation",
    "chinese": "性骚扰\r\n"
}, {
    "english": "voyeurism",
    "chinese": "窥阴癖\r\n"
}, {
    "english": "exhibitionism",
    "chinese": "裸露癖\r\n"
}, {
    "english": "rape",
    "chinese": "强暴\r\n"
}, {
    "english": "about_to_be_raped",
    "chinese": "将要被强暴\r\n"
}, {
    "english": "sex",
    "chinese": "性爱\r\n"
}, {
    "english": "clothed_sex",
    "chinese": "穿着衣服做爱\r\n"
}, {
    "english": "happy_sex",
    "chinese": "快乐做爱\r\n"
}, {
    "english": "underwater_sex",
    "chinese": "水中做爱\r\n"
}, {
    "english": "spitroast",
    "chinese": "前后夹攻\r\n"
}, {
    "english": "cock_in_thighhigh",
    "chinese": "插在过膝袜里\r\n"
}, {
    "english": "69",
    "chinese": "69式\r\n"
}, {
    "english": "doggystyle",
    "chinese": "狗爬式\r\n"
}, {
    "english": "leg_lock/upright_straddle",
    "chinese": "跨坐式\r\n"
}, {
    "english": "missionary",
    "chinese": "传教士体位\r\n"
}, {
    "english": "girl_on_top",
    "chinese": "女上体位\r\n"
}, {
    "english": "cowgirl_position",
    "chinese": "女上正骑\r\n"
}, {
    "english": "reverse_cowgirl",
    "chinese": "女上反骑\r\n"
}, {
    "english": "virgin",
    "chinese": "处女\r\n"
}, {
    "english": "slave",
    "chinese": "奴隶\r\n"
}, {
    "english": "shibari",
    "chinese": "捆绑\r\n"
}, {
    "english": "bondage",
    "chinese": "捆绑/奴役\r\n"
}, {
    "english": "bdsm",
    "chinese": "绑缚与调教/支配与臣服/施虐与受虐\r\n"
}, {
    "english": "pillory/stocks",
    "chinese": "枷锁\r\n"
}, {
    "english": "rope",
    "chinese": "绳子\r\n"
}, {
    "english": "bound_arms",
    "chinese": "手臂捆绑\r\n"
}, {
    "english": "bound_wrists",
    "chinese": "手腕捆绑\r\n"
}, {
    "english": "crotch_rope",
    "chinese": "胯下捆绑\r\n"
}, {
    "english": "hogtie",
    "chinese": "曲膝捆绑\r\n"
}, {
    "english": "frogtie",
    "chinese": "青蛙捆绑\r\n"
}, {
    "english": "suspension",
    "chinese": "悬空捆绑\r\n"
}, {
    "english": "spreader_bar",
    "chinese": "分腿捆绑\r\n"
}, {
    "english": "wooden_horse",
    "chinese": "木马\r\n"
}, {
    "english": "anal_beads",
    "chinese": "肛珠\r\n"
}, {
    "english": "dildo",
    "chinese": "假屌\r\n"
}, {
    "english": "cock_ring",
    "chinese": "屌环\r\n"
}, {
    "english": "egg_vibrator",
    "chinese": "跳蛋\r\n"
}, {
    "english": "artificial_vagina",
    "chinese": "人工阴道\r\n"
}, {
    "english": "hitachi_magic_wand",
    "chinese": "按摩棒\r\n"
}, {
    "english": "dildo",
    "chinese": "人造阴茎\r\n"
}, {
    "english": "double_dildo",
    "chinese": "双头龙\r\n"
}, {
    "english": "vibrator",
    "chinese": "跳蛋\r\n"
}, {
    "english": "vibrator_in_thighhighs",
    "chinese": "跳蛋遥控在过膝袜里\r\n"
}, {
    "english": "nyotaimori",
    "chinese": "女体盛\r\n"
}, {
    "english": "vore",
    "chinese": "吃人\r\n"
}, {
    "english": "amputee",
    "chinese": "截肢\r\n"
}, {
    "english": "transformation",
    "chinese": "肉体变形\r\n"
}, {
    "english": "mind_control",
    "chinese": "思想操控\r\n"
}, {
    "english": "censored",
    "chinese": "审核过的/有码\r\n"
}, {
    "english": "uncensored",
    "chinese": "未审核的/无码\r\n"
}, {
    "english": "asian",
    "chinese": "亚洲\r\n"
}, {
    "english": "faceless_male",
    "chinese": "无脸男\r\n"
}, {
    "english": "blood",
    "chinese": "血"
}]