export default [{
    "english": "girl",
    "chinese": "女孩\r\n"
}, {
    "english": "2girls",
    "chinese": "2女孩\r\n"
}, {
    "english": "3girls",
    "chinese": "3女孩\r\n"
}, {
    "english": "boy",
    "chinese": "男孩\r\n"
},
{
    "english": "chili",
    "chinese": "Q版小人"
}, 
{
    "english": "2boys",
    "chinese": "2男孩\r\n"
}, {
    "english": "3boys",
    "chinese": "3男孩\r\n"
}, {
    "english": "solo",
    "chinese": "单人\r\n"
}, {
    "english": "multiple girls",
    "chinese": "多个\r\n"
}, {
    "english": "little girl",
    "chinese": "小女孩\r\n"
}, {
    "english": "little boy",
    "chinese": "小男孩\r\n"
}, {
    "english": "shota",
    "chinese": "正太\r\n"
}, {
    "english": "loli",
    "chinese": "萝莉\r\n"
}, {
    "english": "kawaii",
    "chinese": "可爱\r\n"
}, {
    "english": "mesugaki",
    "chinese": "雌小鬼\r\n"
}, {
    "english": "adorable girl",
    "chinese": "可爱的女孩\r\n"
}, {
    "english": "bishoujo",
    "chinese": "美少女\r\n"
}, {
    "english": "gyaru",
    "chinese": "辣妹\r\n"
}, {
    "english": "sisters",
    "chinese": "姐妹\r\n"
}, {
    "english": "ojousama",
    "chinese": "大小姐\r\n"
}, {
    "english": "mature female",
    "chinese": "成熟女性\r\n"
}, {
    "english": "mature",
    "chinese": "成熟\r\n"
}, {
    "english": "female pervert",
    "chinese": "痴女\r\n"
}, {
    "english": "milf",
    "chinese": "熟女\r\n"
}, {
    "english": "harem",
    "chinese": "后宫"
}, {
    "english": "angel",
    "chinese": "天使\r\n"
}, {
    "english": "cheerleader",
    "chinese": "啦啦队\r\n"
}, {
    "english": "chibi",
    "chinese": "Q版人物\r\n"
}, {
    "english": "crossdressing",
    "chinese": "伪娘\r\n"
}, {
    "english": "devil",
    "chinese": "魔鬼\r\n"
}, {
    "english": "doll",
    "chinese": "人偶\r\n"
}, {
    "english": "elf",
    "chinese": "妖精\r\n"
}, {
    "english": "fairy",
    "chinese": "小精灵\r\n"
}, {
    "english": "female",
    "chinese": "女人\r\n"
}, {
    "english": "furry",
    "chinese": "兽人\r\n"
}, {
    "english": "orc",
    "chinese": "半兽人\r\n"
}, {
    "english": "giantess",
    "chinese": "女巨人\r\n"
}, {
    "english": "harem",
    "chinese": "后宫\r\n"
}, {
    "english": "idol",
    "chinese": "偶像\r\n"
}, {
    "english": "kemonomimi_mode",
    "chinese": "兽耳萝莉模式\r\n"
}, {
    "english": "loli",
    "chinese": "萝莉\r\n"
}, {
    "english": "magical_girl",
    "chinese": "魔法少女\r\n"
}, {
    "english": "maid",
    "chinese": "女仆\r\n"
}, {
    "english": "male",
    "chinese": "男人\r\n"
}, {
    "english": "mermaid",
    "chinese": "美人鱼\r\n"
}, {
    "english": "miko",
    "chinese": "巫女\r\n"
}, {
    "english": "milf",
    "chinese": "熟女\r\n"
}, {
    "english": "minigirl",
    "chinese": "迷你女孩\r\n"
}, {
    "english": "monster",
    "chinese": "怪物\r\n"
}, {
    "english": "multiple_girls",
    "chinese": "魔幻少女\r\n"
}, {
    "english": "ninja",
    "chinese": "忍者\r\n"
}, {
    "english": "no_humans",
    "chinese": "非人\r\n"
}, {
    "english": "nun",
    "chinese": "修女\r\n"
}, {
    "english": "nurse",
    "chinese": "护士\r\n"
}, {
    "english": "shota",
    "chinese": "正太\r\n"
}, {
    "english": "stewardess",
    "chinese": "空姐\r\n"
}, {
    "english": "student",
    "chinese": "学生\r\n"
}, {
    "english": "trap",
    "chinese": "伪娘\r\n"
}, {
    "english": "vampire",
    "chinese": "吸血鬼\r\n"
}, {
    "english": "waitress",
    "chinese": "女服务员\r\n"
}, {
    "english": "witch",
    "chinese": "女巫\r\n"
}, {
    "english": "yaoi",
    "chinese": "搞基\r\n"
}, {
    "english": "yukkuri_shiteitte_ne",
    "chinese": "油库里\r\n"
}, {
    "english": "yuri",
    "chinese": "百合"
}]