export default [{
    "english": "artbook",
    "chinese": "原画\r\n"
}, {
    "english": "game_cg",
    "chinese": "游戏CG\r\n"
}, {
    "english": "comic",
    "chinese": "漫画\r\n"
}, {
    "english": "4koma",
    "chinese": "四格\r\n"
}, {
    "english": "animated_gif",
    "chinese": "gif格式图片\r\n"
}, {
    "english": "dakimakura",
    "chinese": "抱枕\r\n"
}, {
    "english": "cosplay",
    "chinese": "角色扮演\r\n"
}, {
    "english": "crossover",
    "chinese": "穿越\r\n"
}, {
    "english": "dark",
    "chinese": "暗的\r\n"
}, {
    "english": "light",
    "chinese": "亮的\r\n"
}, {
    "english": "night",
    "chinese": "晚上\r\n"
}, {
    "english": "guro",
    "chinese": "猎奇\r\n"
}, {
    "english": "realistic",
    "chinese": "写实\r\n"
}, {
    "english": "photo",
    "chinese": "照片\r\n"
}, {
    "english": "real",
    "chinese": "真实\r\n"
}, {
    "english": "landscape/scenery",
    "chinese": "风景\r\n"
}, {
    "english": "cityscape",
    "chinese": "城市风景\r\n"
}, {
    "english": "science_fiction",
    "chinese": "科技幻想\r\n"
}, {
    "english": "original",
    "chinese": "原创\r\n"
}, {
    "english": "parody",
    "chinese": "拙劣的模仿\r\n"
}, {
    "english": "personification",
    "chinese": "拟人\r\n"
}, {
    "english": "checkered",
    "chinese": "格子的\r\n"
}, {
    "english": "lowres",
    "chinese": "低分辨率\r\n"
}, {
    "english": "highres",
    "chinese": "高分辨率\r\n"
}, {
    "english": "absurdres",
    "chinese": "超高分辨率\r\n"
}, {
    "english": "incredibly_absurdres",
    "chinese": "极高分辨率\r\n"
}, {
    "english": "huge_filesize",
    "chinese": "超级高分辨率/大文件\r\n"
}, {
    "english": "wallpaper",
    "chinese": "壁纸\r\n"
}, {
    "english": "pixel_art",
    "chinese": "点阵图\r\n"
}, {
    "english": "monochrome",
    "chinese": "单色图片\r\n"
}, {
    "english": "colorful",
    "chinese": "色彩斑斓的\r\n"
}, {
    "english": "optical_illusion",
    "chinese": "视觉错误\r\n"
}, {
    "english": "fine_art_parody",
    "chinese": "名画模仿\r\n"
}, {
    "english": "sketch",
    "chinese": "素描\r\n"
}, {
    "english": "traditional_media",
    "chinese": "传统媒体（基本上是手绘稿）\r\n"
}, {
    "english": "watercolor_(medium)",
    "chinese": "透明水彩绘\r\n"
}, {
    "english": "silhouette",
    "chinese": "剪影\r\n"
}, {
    "english": "covr",
    "chinese": "封面\r\n"
}, {
    "english": "album",
    "chinese": "专辑\r\n"
}, {
    "english": "sample",
    "chinese": "图上有sample字样\r\n"
}, {
    "english": "back",
    "chinese": "背影像\r\n"
}, {
    "english": "bust",
    "chinese": "半身像\r\n"
}, {
    "english": "profile",
    "chinese": "侧面绘\r\n"
}, {
    "english": "expressions",
    "chinese": "表情绘（各种表情）\r\n"
}, {
    "english": "everyone",
    "chinese": "一部作品中的主要人物集齐\r\n"
}, {
    "english": "column_lineup",
    "chinese": "一列列小图组成大图\r\n"
}, {
    "english": "transparent_background",
    "chinese": "透明的背景(.png)\r\n"
}, {
    "english": "simple_background",
    "chinese": "简单的背景(无背景)\r\n"
}, {
    "english": "gradient_background",
    "chinese": "渐变的背景\r\n"
}, {
    "english": "zoom_layer",
    "chinese": "背景是前景的放大版\r\n"
}, {
    "english": "English",
    "chinese": "英文\r\n"
}, {
    "english": "Chinese",
    "chinese": "中文\r\n"
}, {
    "english": "French",
    "chinese": "法文\r\n"
}, {
    "english": "Japanese",
    "chinese": "日本人\r\n"
}, {
    "english": "translation_request",
    "chinese": "翻译\r\n"
}, {
    "english": "bad_id",
    "chinese": "ID转向错误(原地址或已被删除)\r\n"
}, {
    "english": "tagme",
    "chinese": "图片有一些上传者未知的项目\r\n"
}, {
    "english": "artist_request",
    "chinese": "作者未知,需要补完\r\n"
}, {
    "english": "what",
    "chinese": "不知所谓"
}]